# Generated by Django 5.2.8 on 2025-11-25 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone_whatsapp', models.CharField(max_length=20)),
                ('chave_pix', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('registro_profissional', models.CharField(help_text='CRP, OAB, CRM etc.', max_length=50)),
                ('imagem_cabecalho', models.ImageField(blank=True, null=True, upload_to='cabecalhos/')),
                ('tipo_consulta', models.CharField(choices=[('medico', 'Médico'), ('psicologo', 'Psicólogo'), ('nutricionista', 'Nutricionista'), ('advogado', 'Advogado')], max_length=50)),
                ('dias_nao_atende', models.TextField(help_text='Informe os dias que não atende (ex: sábado, domingo)')),
                ('valor_consulta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
