# Generated by Django 5.2.8 on 2025-11-25 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMedApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone_whatsapp', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('status', models.CharField(choices=[('marcado', 'Marcado'), ('cancelado', 'Cancelado'), ('remarcado', 'Remarcado')], default='marcado', max_length=20)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMedApp.profissional')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMedApp.paciente')),
            ],
        ),
    ]
